# Generated by Django 4.2.3 on 2023-08-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
