# Generated by Django 4.1.10 on 2023-08-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_track_material_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.track')),
            ],
        ),
    ]
