# Generated by Django 4.1.10 on 2023-08-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.FileField(upload_to='Tasks/')),
                ('deadline', models.TimeField()),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
