# Generated by Django 4.1.10 on 2023-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_courses_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video/poster/'),
        ),
    ]
