# Generated by Django 4.1.10 on 2023-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_courses_title_alter_courses_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levels',
            name='content',
        ),
        migrations.AddField(
            model_name='levels',
            name='course',
            field=models.ManyToManyField(to='pages.courses'),
        ),
    ]
