# Generated by Django 4.1.10 on 2023-08-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_skills'),
        ('accounts', '0005_alter_user_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.levels'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.task'),
        ),
    ]
